config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: %w[ show ] do
        member do
          get 'following'
          get 'followers'
        end
      end
    end
  end

  resources :users, only: %w[ show ] do
    member do
      get 'follow'
      get 'following'
      get 'followers'
    end
  end

  resources :posts, only: %w[ create ]

  root 'welcome#index'
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
end

app/models/follow_relationship.rb
class FollowRelationship < ActiveRecord::Base
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :content, presence: true, length: { maximum: 160 }
  validates :user_id, presence: true

  belongs_to :user

  default_scope { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email,    presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true,
                      message: "is invalid Only letter, number, underscore and punctuation."

  has_many :posts, dependent: :destroy
  has_many :following_relationships, class_name:  "FollowRelationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy

  has_many :followers_relationships, class_name:  "FollowRelationship",
                                     foreign_key: "followed_id",
                                     dependent:   :destroy

  has_many :following, through: :following_relationships, source: :followed
  has_many :followers, through: :followers_relationships, source: :follower

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["username = :value OR email = :value", { :value => login }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username
  end

  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    Post.where("EXISTS(SELECT *
                       FROM follow_relationships
                       WHERE (posts.user_id = #{self.id}) OR
                             (follow_relationships.follower_id = #{self.id} AND
                              follow_relationships.followed_id = posts.user_id))")
  end
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
      before_filter :restrict_access
      respond_to :json

      private

      def restrict_access
        authenticate_or_request_with_http_token do |token, options|
          ApiKey.exists?(access_token: token)
        end
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseController
      before_filter :set_user

      def show
        respond_with @user.posts
      end

      def followers
        respond_with @user.followers
      end

      def following
        respond_with @user.following
      end

      private

      def set_user
        @user = User.find(params[:id])
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!

  layout false, only: %w[ create ]

  def create
    @post = Post.create!(post_params)

    render partial: 'post', locals: { post: @post }
  end

  private

  def post_params
    params[:post].permit(:content).merge({ user_id: current_user.id })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_user
  before_filter :set_counters, except: %w[ follow ]

  layout false, only: %w[ follow ]

  def show
    @posts = @user.posts
  end

  def followers
    @followers = @user.followers
  end

  def following
    @following = @user.following
  end

  def follow
    if current_user.following?(@user)
      current_user.unfollow(@user)
    else
      current_user.follow(@user)
    end

    set_counters

    render nothing: true
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_counters
    @followers_count = @user.followers.count
    @following_count = @user.following.count
    @posts_count     = @user.posts.count
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, except: %w[ index ]
  before_filter :index_redirection, only: %W[ index ]

  def index
    @posts = current_user.feed
  end

  private

  def index_redirection
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_content.html.haml
#content
  %div.container
    %p{ class: "notice" }
      = notice
    %p{ class: "alert" }
      = alert
    = yield

app/views/application/_footer.html.haml
%footer{ id: 'footer' }
  .container
    %p
      Brought to <em>You</em> by <strong>Mojarra</strong>
      &mdash;
      %em
        Powered by
        = fa_icon('cogs')
        = link_to '@MojarraGandhi', 'http://twitter.com/MojarraGandhi', target: '_blank'

app/views/application/_header.html.haml
#header.navbar.navbar-default.navbar-inverse.navbar-static-top
  .container
    .navbar-header
      %button{ 'type'        => "button",
               'class'       => "navbar-toggle",
               'data-toggle' => "collapse",
               'data-target' => ".navbar-collapse" }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: "navbar-brand", id: "logo" do
        Platform161 | SocialNet

    = render partial: "user_dropdown_menu"  if user_signed_in?

app/views/application/_user_dropdown_menu.html.haml
.collapse.navbar-collapse
  %ul.nav.navbar-nav.navbar-right
    %li.dropdown
      %a.dropdown-toggle{ 'role'          => "button",
                          'href'          => "#",
                          'data-toggle'   => "dropdown",
                          'aria-haspopup' => "true",
                          'aria-expanded' => "false" }

        = current_user.username
        %span.caret
      %ul.dropdown-menu
        %li.dropdown-header
          logged in as
          %strong
            = " #{current_user.username}"
          %li.divider
        %li
          = link_to destroy_user_session_path, method: :delete do
            Logout

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Platform161 | SocialNet
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'header'
    = render 'content'
    = render 'footer'

app/views/posts/_post.html.haml
%li{ id: "post-#{post.id}" }
  %span.user
    = link_to post.user.username, post.user
  %span.content
    = post.content
  %span.timestamp
    Posted
    = "#{time_ago_in_words(post.created_at)} ago."

app/views/posts/_post_form.html.haml
= form_for(Post.new) do |f|
  .form-group
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-primary"

app/views/users/_user.html.haml
%li{ id: "user-#{user.id}" }
  %span.user
    = link_to "#{user.username}(#{user.email})", user
  %span.stats
    Posts #{user.posts.count} | Following #{user.following.count} | Followers #{user.followers.count}
  %span.timestamp
    Signed Up
    = "#{time_ago_in_words(user.created_at)} ago."

app/views/users/_wall_header.html.haml
%h1
  #{@user.username}(#{@user.email})
  - unless @user == current_user
    %span.pull-right
      = link_to "#{current_user.following?(@user) ? 'Unf' : 'F'}ollow", "#",
                class: "btn btn-primary follow-btn",
                "data-user-id" => @user.id
%h4
  = link_to "Posts(#{@posts_count})", user_path(@user),
            class: "#{'active' if current_page?(action: :show)}"
  |
  = link_to "Following(#{@following_count})", following_user_path(@user),
             class: "#{'active' if current_page?(action: :following)}"
  |
  = link_to "Followers(#{@followers_count})", followers_user_path(@user),
             class: "#{'active' if current_page?(action: :followers)}"

app/views/users/followers.html.haml
#wall-header
  = render partial: "wall_header"
%ol.users
  = render @followers

app/views/users/following.html.haml
#wall-header
  = render partial: "wall_header"
%ol.users
  = render @following

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/show.html.haml
#wall-header
  = render partial: "wall_header"
%ol.wall
  = render @posts

app/views/welcome/index.html.haml
= form_for Post.new do |f|
  .form-group
    = f.text_area :content, class: "new-post", placeholder: "What are you thinking..."
  .form-group.pull-right
    = f.submit "Post", class: "btn btn-primary new-post-btn"
%h2.last-news
  Last News
%ol#last-news.wall
  = render @posts